-- AlterTable
ALTER TABLE "GlobalProfile" ADD COLUMN     "bans" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "kicks" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "mutes" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "reputation" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN     "warns" INTEGER NOT NULL DEFAULT 0;
